accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Zlib",
    "Unicode-3.0",
]

workarounds = [
    "ring"
]

[ring]
accepted = ["MIT", "OpenSSL", "ISC", "NOASSERTION"]

# This validated against webpki 0.22.0 however
# this version is not visible in https://github.com/briansmith/webpki.
# The source code and license is visible via https://docs.rs/webpki/0.22.0/webpki/.
[webpki.clarify]
license = "ISC"

[[webpki.clarify.files]]
license = "ISC"
path = 'LICENSE'
checksum = "5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a"
